name: restaurant_kot
description: "for restaurant kot Mang"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^4.0.4
  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.3
  flutter_screenutil: ^5.9.3
  bloc: ^8.1.4
  mssql_connection: ^1.1.3
  infinite_scroll_pagination: ^4.0.0
  flutter_esc_pos_network: ^1.0.3
  flutter_esc_pos_utils: ^1.0.1
  http: ^1.2.2
  lucide_icons: ^0.257.0
  screenshot: ^3.0.0
  barcode: ^2.0.0
  barcode_image: ^2.0.0
  excel: ^2.0.1
  url_launcher: ^6.3.1
  qr_code_scanner_plus: ^2.0.10+1
  flutter_animate: ^4.5.2
  network_info_plus: ^6.1.4
  sqflite: ^2.4.2
  file_picker: ^10.3.1
  permission_handler: ^11.3.0
  path_provider: ^2.1.2









  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.9

flutter:

  uses-material-design: true

  # Custom Fonts
  fonts:
    - family: Montserrat  # Name your font family
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf  # Path to the regular font
        - asset: assets/fonts/Montserrat-Bold.ttf     # Path to the bold font
          weight: 600  # Weight for bold font
        - asset: assets/fonts/Montserrat-Italic.ttf   # Path to the italic font
          style: italic  # Style for italic font

  # Assets
  assets:
    - assets/fonts/
    - assets/img/table/
    - assets/img/loginpage/
    - assets/img/logo/
    - assets/img/no data/
    - assets/img/printer/
    - assets/img/profile/ 
    - assets/mp3/






